version: "3.9"
services:
  db:
    image: postgres
    container_name: Todo-DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=credentials
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports: 
      - "5431:5432"
  web:
    build: .
    container_name: Todo-Auth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - todoDB
volumes:
  postgres_data:
    driver:local