# Generated by Django 3.2.4 on 2021-08-23 12:03

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=128)),
                ('lastname', models.CharField(db_index=True, max_length=128)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_admin', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 8, 23, 17, 33, 8, 78834), max_length=256)),
            ],
            options={
                'db_table': 'admin_credentials',
            },
        ),
        migrations.CreateModel(
            name='BlacklistTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist', models.CharField(db_index=True, max_length=512)),
            ],
            options={
                'db_table': 'blacklist_tokens',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('firstname', models.CharField(db_index=True, max_length=128)),
                ('lastname', models.CharField(db_index=True, max_length=128)),
                ('feedback', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=2048), size=None)),
            ],
            options={
                'db_table': 'user_feedback',
            },
        ),
        migrations.CreateModel(
            name='RegisterTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.CharField(max_length=512)),
                ('user_id', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'register_tokens',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=128)),
                ('lastname', models.CharField(db_index=True, max_length=128)),
                ('email', models.CharField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2021, 8, 23, 17, 33, 8, 76838), max_length=256)),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
    ]
