# Generated by Django 3.2.4 on 2021-06-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
    ]
