# Generated by Django 3.2.4 on 2021-06-28 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210628_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 13, 10, 39, 50247), max_length=256),
        ),
    ]
